"""add numberplate damage ppe columns

Revision ID: 0018
Revises: 0017
Create Date: 2026-07-28 08:16:38.557245
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_count_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_numberplate', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('detect_damage_parcel', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('detect_ppe', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('numberplate_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('damage_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ppe_results', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('object_count_media', schema=None) as batch_op:
        batch_op.drop_column('ppe_results')
        batch_op.drop_column('damage_results')
        batch_op.drop_column('numberplate_results')
        batch_op.drop_column('detect_ppe')
        batch_op.drop_column('detect_damage_parcel')
        batch_op.drop_column('detect_numberplate')

    # ### end Alembic commands ###
