"""add_activity_granular_columns

Revision ID: 0019
Revises: 0018
Create Date: 2026-08-03 06:51:57.527560
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0019'
down_revision = '0018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_sitting', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('detect_fighting', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('detect_smoking', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('detect_phone_usage', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.drop_column('detect_phone_usage')
        batch_op.drop_column('detect_smoking')
        batch_op.drop_column('detect_fighting')
        batch_op.drop_column('detect_sitting')

    # ### end Alembic commands ###
